export const Images = {
    '蘋果': require('../assets/FridgeFood/apple.png'),
    '豆腐': require('../assets/FridgeFood/tofu.png'),
    '葡萄': require('../assets/FridgeFood/grape.jpg'),
    '鳳梨': require('../assets/FridgeFood/pineapple.png'),
    '蝦子': require('../assets/FridgeFood/shrimp.png'),
    '酪梨': require('../assets/FridgeFood/avocado.jpeg'),
    '鮮魚': require('../assets/FridgeFood/fish.png'),
    '牛肉': require('../assets/FridgeFood/beaf.png'),
    '豬肉': require('../assets/FridgeFood/pork.png'),
    '雞肉': require('../assets/FridgeFood/chicken.png'),
    '絲瓜炒牛肉': require('../assets/Recipe/絲瓜炒牛肉.jpg'),
    '螞蟻上樹': require('../assets/Recipe/螞蟻上樹.jpeg'),
    '清蒸鮮石斑': require('../assets/Recipe/清蒸石斑.jpg'),
    '炒菠菜': require('../assets/Recipe/炒菠菜.jpeg'),
    '重慶水煮牛': require('../assets/Recipe/麻辣水煮牛.jpeg'),
    '海鮮羹': require('../assets/Recipe/海鮮羹.jpg'),
    '滑蛋豬肉丼飯': require('../assets/Recipe/滑蛋豬肉丼飯.jpeg'),
    '茶碗蒸': require('../assets/Recipe/茶碗蒸.jpeg'),
    '牛肉漢堡排': require('../assets/Recipe/漢堡.jpeg'),
    '明太子奶香義大利麵': require('../assets/Recipe/義大利麵.jpeg'),
    '肉絲蛋炒飯': require('../assets/Recipe/炒飯.jpg'),

}